"""
batch_predict.py

Select a trained model and run batch prediction on all prepared predict recordings.
Picks up where prepare_data.py --mode predict left off.

All settings are controlled by config.py — do not edit this file directly.

Usage:
    # Interactive model selection menu
    python petrel_detection/batch_predict.py

    # Specify model directly by results directory name
    python petrel_detection/batch_predict.py --model results_260417_204919

    # Also generate downstream time-of-arrival statistics
    python petrel_detection/batch_predict.py --downstream
"""

import os
import sys
import argparse
import subprocess
from pathlib import Path

import tomlkit

# ── Load config ───────────────────────────────────────────────────────────────

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from config import (
    VAK_PYTHON,
    PREDICT_TOML,
    SEGMENT_ROOT,
    PREP_PREDICT_DIR,
    TRAIN_RESULTS_ROOT,
    PREDICT_CSV_DIR,
    RAVEN_TABLE_DIR,
    SEGMENT_DURATION,
    PETREL_SCRIPTS_DIR,
    DOWNSTREAM_SUFFIX,
    DOWNSTREAM_OUTPUT_DIR,
)

sys.path.insert(0, PETREL_SCRIPTS_DIR)
from generate_tables import run_generate_tables
try:
    from downstream import run_downstream
    HAS_DOWNSTREAM = True
except ImportError:
    HAS_DOWNSTREAM = False


# ── Model selection ───────────────────────────────────────────────────────────

def list_available_models() -> list[Path]:
    root = Path(TRAIN_RESULTS_ROOT)
    if not root.exists():
        return []
    return sorted(
        [d for d in root.iterdir() if d.is_dir() and d.name.startswith("results_")],
        key=lambda d: d.stat().st_mtime,
        reverse=True,
    )


def validate_model_dir(results_dir: Path) -> tuple[str, str, str]:
    ckpt         = results_dir / "TweetyNet" / "checkpoints" / "max-val-acc-checkpoint.pt"
    labelmap     = results_dir / "labelmap.json"
    standardizer = results_dir / "FramesStandardizer"
    missing = [n for p, n in [(ckpt, "max-val-acc-checkpoint.pt"),
                               (labelmap, "labelmap.json"),
                               (standardizer, "FramesStandardizer")] if not p.exists()]
    if missing:
        raise FileNotFoundError(f"Model '{results_dir.name}' is missing: {', '.join(missing)}")
    return str(ckpt), str(labelmap), str(standardizer)


def _format_mtime(path: Path) -> str:
    import datetime
    return datetime.datetime.fromtimestamp(path.stat().st_mtime).strftime("%Y-%m-%d %H:%M")


def select_model_interactive() -> Path:
    models = list_available_models()
    if not models:
        raise FileNotFoundError(
            f"No trained models found in {TRAIN_RESULTS_ROOT}. "
            "Run run_experiment.py first."
        )

    print("\nAvailable trained models (newest first):\n")
    for i, m in enumerate(models):
        marker = "  [latest]" if i == 0 else ""
        print(f"  [{i}] {m.name}  ({_format_mtime(m)}){marker}")

    print()
    while True:
        raw = input("Enter model number (or press Enter for latest): ").strip()
        if raw == "":
            return models[0]
        try:
            choice = int(raw)
            if 0 <= choice < len(models):
                print(f"\n  Selected: {models[choice].name}")
                return models[choice]
        except ValueError:
            pass
        print(f"  Please enter a number between 0 and {len(models) - 1}.")


# ── Config updater ────────────────────────────────────────────────────────────

def update_predict_toml(
    recorder_name: str,
    prep_dataset_path: str,
    checkpoint_path: str,
    labelmap_path: str,
    standardizer_path: str,
):
    with open(PREDICT_TOML, "r", encoding="utf-8") as f:
        config = tomlkit.load(f)
    config["vak"]["predict"]["checkpoint_path"]          = checkpoint_path
    config["vak"]["predict"]["labelmap_path"]            = labelmap_path
    config["vak"]["predict"]["frames_standardizer_path"] = standardizer_path
    config["vak"]["predict"]["output_dir"]               = PREDICT_CSV_DIR
    config["vak"]["predict"]["annot_csv_filename"]       = f"{recorder_name}.annot.csv"
    config["vak"]["predict"]["dataset"]["path"]          = prep_dataset_path
    with open(PREDICT_TOML, "w", encoding="utf-8") as f:
        tomlkit.dump(config, f)


def find_prep_dataset(recorder_name: str) -> str:
    prep_root  = Path(PREP_PREDICT_DIR)
    candidates = sorted(
        [d for d in prep_root.iterdir() if d.is_dir() and d.name.startswith(recorder_name)],
        key=lambda d: d.stat().st_mtime,
    )
    if not candidates:
        raise FileNotFoundError(
            f"No prepared dataset found for '{recorder_name}' in {PREP_PREDICT_DIR}.\n"
            "Run prepare_data.py --mode predict first."
        )
    return str(candidates[-1])


# ── Batch prediction ──────────────────────────────────────────────────────────

def run_batch_predict(checkpoint_path: str, labelmap_path: str, standardizer_path: str) -> list[str]:
    predict_root = Path(SEGMENT_ROOT) / "predict_data"
    if not predict_root.exists():
        raise FileNotFoundError(
            f"Predict segment directory not found: {predict_root}\n"
            "Run prepare_data.py --mode predict first."
        )

    recorders = sorted([d for d in predict_root.iterdir() if d.is_dir()])
    if not recorders:
        raise FileNotFoundError(f"No recorder subdirectories found in {predict_root}")

    print(f"\nFound {len(recorders)} recorder(s): {[r.name for r in recorders]}")
    os.makedirs(PREDICT_CSV_DIR, exist_ok=True)

    succeeded, failed = [], []

    for i, rec_dir in enumerate(recorders, 1):
        recorder_name = rec_dir.name
        print(f"\n[{i}/{len(recorders)}] {recorder_name}")
        try:
            prep_path = find_prep_dataset(recorder_name)
            print(f"  Prep dataset : {Path(prep_path).name}")
            update_predict_toml(recorder_name, prep_path, checkpoint_path, labelmap_path, standardizer_path)
            print(f"  Config updated ✓")
            subprocess.run([VAK_PYTHON, "-m", "vak", "predict", PREDICT_TOML], check=True)
            print(f"  Prediction complete ✓")
            succeeded.append(recorder_name)
        except FileNotFoundError as e:
            print(f"  ⚠ Skipped: {e}")
            failed.append(recorder_name)
        except subprocess.CalledProcessError as e:
            print(f"  ❌ vak predict failed: {e}")
            failed.append(recorder_name)

    if failed:
        print(f"\n⚠ Failed recorders: {failed}")
    return succeeded


# ── Post-processing ───────────────────────────────────────────────────────────

def run_raven_tables(recorder_names: list[str]):
    print("\n" + "=" * 60)
    print("Generating Raven annotation tables")
    print("=" * 60)
    os.makedirs(RAVEN_TABLE_DIR, exist_ok=True)
    for recorder_name in recorder_names:
        annot_csv = Path(PREDICT_CSV_DIR) / f"{recorder_name}.annot.csv"
        if not annot_csv.exists():
            print(f"  ⚠ {recorder_name}: prediction CSV not found, skipping")
            continue
        raven_path = run_generate_tables(
            predict_csv_path=str(annot_csv),
            output_dir=RAVEN_TABLE_DIR,
            segment_duration=SEGMENT_DURATION,
            tag=recorder_name,
        )
        if raven_path:
            print(f"  ✓ {recorder_name} → {Path(raven_path).name}")
        else:
            print(f"  ⚠ {recorder_name}: table generation failed")


def run_downstream_stats():
    if not HAS_DOWNSTREAM:
        print("\n⚠ downstream.py not importable — skipping downstream stats")
        return
    print("\n" + "=" * 60)
    print("Generating downstream time-of-arrival statistics")
    print("=" * 60)
    try:
        run_downstream(
            input_dir  = RAVEN_TABLE_DIR,
            output_dir = DOWNSTREAM_OUTPUT_DIR,
            suffix     = DOWNSTREAM_SUFFIX,
        )
        print(f"  ✓ Downstream stats complete → {DOWNSTREAM_OUTPUT_DIR}")
    except Exception as e:
        print(f"  ❌ Downstream failed: {e}")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Select a trained model and run batch prediction on all predict recordings"
    )
    parser.add_argument(
        "--model",
        default=None,
        help="Name of results directory (e.g. results_260417_204919). "
             "If omitted, an interactive selection menu is shown.",
    )
    parser.add_argument(
        "--downstream",
        action="store_true",
        help="Also generate downstream time-of-arrival statistics after prediction",
    )
    args = parser.parse_args()

    print("\n" + "=" * 60)
    print("batch_predict.py — Batch Prediction Pipeline")
    print("=" * 60)

    if args.model:
        results_dir = Path(TRAIN_RESULTS_ROOT) / args.model
        if not results_dir.exists():
            raise FileNotFoundError(f"Model directory not found: {results_dir}")
        print(f"\nUsing specified model: {results_dir.name}")
    else:
        results_dir = select_model_interactive()

    checkpoint_path, labelmap_path, standardizer_path = validate_model_dir(results_dir)
    print(f"\nModel artefacts from: {results_dir.name}")

    print("\n" + "=" * 60)
    print("Running batch prediction")
    print("=" * 60)
    succeeded = run_batch_predict(checkpoint_path, labelmap_path, standardizer_path)

    if not succeeded:
        print("\n❌ No recorders were successfully predicted.")
        return

    run_raven_tables(succeeded)

    if args.downstream:
        run_downstream_stats()

    print("\n" + "=" * 60)
    print(f"✅ Batch prediction complete")
    print(f"   Model        : {results_dir.name}")
    print(f"   Recorders    : {len(succeeded)} succeeded")
    print(f"   Raven tables : {RAVEN_TABLE_DIR}")
    if args.downstream:
        print(f"   Downstream   : {DOWNSTREAM_OUTPUT_DIR}")
    print("=" * 60)


if __name__ == "__main__":
    main()