"""
downstream.py

Convert annotation times from Raven prediction tables to seconds relative to
06:00:00 of the recording day, using per-recorder start times from an Excel file.

All settings are controlled by config.py — do not edit this file directly.

Can be run standalone or called from batch_predict.py via run_downstream().

Usage (standalone):
    python petrel_detection/downstream.py
"""

import os
import re
import sys
from pathlib import Path

import pandas as pd
from datetime import datetime

# ── Load config ───────────────────────────────────────────────────────────────

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from config import (
    RECORDING_START_XLSX,
    DOWNSTREAM_SUFFIX,
    DOWNSTREAM_INPUT_DIR,
    DOWNSTREAM_OUTPUT_DIR,
)

BASELINE_HOUR = 6   # Seconds are measured from 06:00:00


# ── Core Functions ────────────────────────────────────────────────────────────

def load_start_times(xlsx_path: str) -> dict:
    """Read Excel file and return {file_name: start_time string} dictionary."""
    df = pd.read_excel(xlsx_path, dtype=str)
    return dict(zip(df['file_name'].str.strip(), df['start_time'].str.strip()))


def parse_start_time_to_seconds(start_time_str: str) -> float:
    """
    Convert HH:MM:SS.f to seconds relative to 06:00:00 of the same day.
    Example: '08:14:35.852' → 8075.852
    """
    t = datetime.strptime(start_time_str, "%H:%M:%S.%f")
    baseline = t.replace(hour=BASELINE_HOUR, minute=0, second=0, microsecond=0)
    return (t - baseline).total_seconds()


def convert_one_file(txt_path: str, start_times_dict: dict) -> pd.DataFrame | None:
    """
    Process a single Raven prediction table.
    Returns a DataFrame with columns [Recorder, start, end], or None if skipped.
    """
    basename = os.path.basename(txt_path)

    # Extract recorder number (e.g. r01 → 1)
    recorder_match = re.match(r'r(\d+)_', basename, re.IGNORECASE)
    if not recorder_match:
        print(f"  ⚠ Skipped (cannot parse recorder ID): {basename}")
        return None
    recorder = int(recorder_match.group(1))

    # Extract file_name key (e.g. r01_250505055705)
    file_name_match = re.match(r'(r\d+_\d+)', basename, re.IGNORECASE)
    if not file_name_match:
        print(f"  ⚠ Skipped (cannot parse file name): {basename}")
        return None
    file_name = file_name_match.group(1)

    if file_name not in start_times_dict:
        print(f"  ⚠ Skipped (not found in Excel: {file_name}): {basename}")
        return None

    recording_offset_s = parse_start_time_to_seconds(start_times_dict[file_name])

    df = pd.read_csv(txt_path, sep='\t')
    df.columns = df.columns.str.strip()

    if 'Annotation' in df.columns:
        df = df[df['Annotation'] == 'p'].copy()

    if df.empty:
        print(f"  ⚠ Skipped (no valid annotations): {basename}")
        return None

    out_df = pd.DataFrame({
        'Recorder': recorder,
        'start': (recording_offset_s + df['Begin Time (s)'].astype(float)).round(3).values,
        'end':   (recording_offset_s + df['End Time (s)'].astype(float)).round(3).values,
    })

    return out_df


def batch_convert(input_dir: str, output_dir: str, suffix: str = DOWNSTREAM_SUFFIX):
    """
    Process all Raven prediction tables matching `suffix` in `input_dir`.
    Writes one CSV per recorder and a merged master file to `output_dir`.
    """
    os.makedirs(output_dir, exist_ok=True)

    start_times_dict = load_start_times(RECORDING_START_XLSX)
    print(f"  Loaded {len(start_times_dict)} recording start times from Excel")

    txt_files = sorted([
        os.path.join(input_dir, f)
        for f in os.listdir(input_dir)
        if f.endswith(suffix)
    ])

    if not txt_files:
        print(f"  ❌ No files matching '*{suffix}' found in: {input_dir}")
        return

    print(f"  Found {len(txt_files)} file(s), processing...\n")

    all_dfs = []
    for txt_path in txt_files:
        print(f"  Processing: {os.path.basename(txt_path)}")
        df = convert_one_file(txt_path, start_times_dict)
        if df is not None:
            base = os.path.basename(txt_path).replace(suffix, '')
            single_path = os.path.join(output_dir, f"{base}_stats.csv")
            df.to_csv(single_path, index=False)
            print(f"    ✓ {len(df)} records → {os.path.basename(single_path)}")
            all_dfs.append(df)

    if all_dfs:
        merged = pd.concat(all_dfs, ignore_index=True)
        merged = merged.sort_values(['Recorder', 'start']).reset_index(drop=True)
        merged_path = os.path.join(output_dir, "all_merged_stats.csv")
        merged.to_csv(merged_path, index=False)
        print(f"\n  ✓ Merged file: {merged_path} ({len(merged)} total records)")
    else:
        print("\n  ❌ No files processed successfully.")


# ── Entry point for batch_predict.py ─────────────────────────────────────────

def run_downstream(input_dir: str, output_dir: str, suffix: str = None):
    """
    Called by batch_predict.py after prediction completes.
    Wraps batch_convert() with optional suffix override.
    """
    batch_convert(
        input_dir  = input_dir,
        output_dir = output_dir,
        suffix     = suffix if suffix is not None else DOWNSTREAM_SUFFIX,
    )


# ── Standalone entry point ────────────────────────────────────────────────────

if __name__ == "__main__":
    print("\n" + "=" * 60)
    print("downstream.py — Standalone Mode")
    print(f"  Input  : {DOWNSTREAM_INPUT_DIR}")
    print(f"  Output : {DOWNSTREAM_OUTPUT_DIR}")
    print(f"  Suffix : {DOWNSTREAM_SUFFIX}")
    print("=" * 60 + "\n")

    batch_convert(
        input_dir  = DOWNSTREAM_INPUT_DIR,
        output_dir = DOWNSTREAM_OUTPUT_DIR,
        suffix     = DOWNSTREAM_SUFFIX,
    )
