"""
prepare_data.py

Batch data preparation pipeline for petrel detection project.
Supports three modes: training, test, predict

All settings are controlled by config.py — do not edit this file directly.

Usage:
    python petrel_detection/prepare_data.py --mode train
    python petrel_detection/prepare_data.py --mode test
    python petrel_detection/prepare_data.py --mode predict
"""

import os
import re
import csv
import argparse
import subprocess
import shutil
import sys
from pathlib import Path

import tomlkit
from pydub import AudioSegment

# ── Load config ───────────────────────────────────────────────────────────────

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from config import (
    VAK_PYTHON,
    TRAIN_TOML,
    PREDICT_TOML,
    SEGMENT_ROOT,
    SEGMENT_DURATION,
    PREP_TRAIN_DIR,
    PREP_TEST_DIR,
    PREP_PREDICT_DIR,
    TRAIN_DUR,
    VAL_DUR,
    TEST_DUR,
    RAW_AUDIO_TRAIN,
    RAW_AUDIO_TEST,
    RAW_AUDIO_PREDICT,
    RAW_ANNOT_TRAIN,
    RAW_ANNOT_TEST,
    ACCELERATOR,
    DEVICES
)

# ── Raven Annotation Parser ───────────────────────────────────────────────────

def parse_raven_annotations(annot_path: str) -> list[dict]:
    """
    Parse a Raven Pro annotation table (.txt, tab-separated).
    Returns a list of dicts with keys: begin_time, end_time, label
    """
    annotations = []
    with open(annot_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f, delimiter="\t")
        for row in reader:
            # Raven column names (case-insensitive search)
            keys = {k.lower(): k for k in row.keys()}
            begin_key = keys.get("begin time (s)") or keys.get("begin time(s)")
            end_key   = keys.get("end time (s)")   or keys.get("end time(s)")

            # Fallback: search for columns containing "begin" and "end"
            if begin_key is None:
                for k in keys:
                    if "begin" in k and "time" in k:
                        begin_key = keys[k]
                        break
            if end_key is None:
                for k in keys:
                    if "end" in k and "time" in k:
                        end_key = keys[k]
                        break

            if begin_key is None or end_key is None:
                raise ValueError(
                    f"Cannot find Begin/End Time columns in {annot_path}. "
                    f"Available columns: {list(row.keys())}"
                )

            annotations.append({
                "begin_time": float(row[begin_key]),
                "end_time":   float(row[end_key]),
                "label":      "p",
            })
    return annotations


# ── Audio Splitter ────────────────────────────────────────────────────────────

def split_audio_and_annotations(
    audio_path: str,
    output_dir: str,
    annot_path: str | None = None,
    segment_duration: int = SEGMENT_DURATION,
) -> list[str]:
    """
    Split a long wav file into fixed-length segments.
    If annot_path is provided, also generates a .csv annotation file per segment.

    Returns list of output segment wav paths.
    """
    audio_path  = Path(audio_path)
    output_dir  = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    print(f"  Loading audio: {audio_path.name}")
    audio = AudioSegment.from_wav(str(audio_path))
    total_ms  = len(audio)
    seg_ms    = segment_duration * 1000

    # Parse annotations once (if provided)
    annotations = parse_raven_annotations(str(annot_path)) if annot_path else []

    segment_paths = []
    seg_idx = 1

    for start_ms in range(0, total_ms, seg_ms):
        end_ms    = min(start_ms + seg_ms, total_ms)
        seg_audio = audio[start_ms:end_ms]

        seg_name = f"seg{seg_idx:03d}.wav"
        seg_path = output_dir / seg_name
        seg_audio.export(str(seg_path), format="wav")
        segment_paths.append(str(seg_path))

        # Write annotation CSV (only when annotations are provided)
        if annotations:
            seg_start_s = start_ms / 1000.0
            seg_end_s   = end_ms   / 1000.0

            csv_path = output_dir / f"{seg_name}.csv"
            with open(csv_path, "w", newline="", encoding="utf-8") as f:
                writer = csv.writer(f)
                writer.writerow(["onset_s", "offset_s", "label"])
                for ann in annotations:
                    # Include annotations that overlap with this segment
                    if ann["end_time"] > seg_start_s and ann["begin_time"] < seg_end_s:
                        onset  = max(ann["begin_time"] - seg_start_s, 0.0)
                        offset = min(ann["end_time"]   - seg_start_s, seg_end_s - seg_start_s)
                        writer.writerow([f"{onset:.6f}", f"{offset:.6f}", ann["label"]])

        seg_idx += 1

    print(f"    → {seg_idx - 1} segments written to {output_dir}")
    return segment_paths


# ── Find matching annotation file ─────────────────────────────────────────────

def find_annotation(audio_stem: str, annot_dir: Path) -> Path | None:
    """
    Find a Raven annotation file matching an audio stem.
    Supports .txt extensions; matches on stem substring.
    """
    for f in annot_dir.iterdir():
        if f.suffix.lower() == ".txt" and audio_stem.lower() in f.stem.lower():
            return f
    # Looser match: annotation stem contains audio stem
    for f in annot_dir.iterdir():
        if f.suffix.lower() == ".txt" and f.stem.lower() in audio_stem.lower():
            return f
    return None


# ── TOML updaters ─────────────────────────────────────────────────────────────

def update_train_toml(data_dir: str):
    """Update config_train.toml with new data_dir and reset dataset path."""
    with open(TRAIN_TOML, "r", encoding="utf-8") as f:
        config = tomlkit.load(f)

    config["vak"]["prep"]["data_dir"]   = data_dir
    config["vak"]["prep"]["output_dir"] = PREP_TRAIN_DIR
    config["vak"]["prep"]["train_dur"]  = TRAIN_DUR
    config["vak"]["prep"]["val_dur"]    = VAL_DUR
    config["vak"]["prep"]["test_dur"]   = TEST_DUR
    config["vak"]["train"]["trainer"]["accelerator"] = ACCELERATOR
    config["vak"]["train"]["trainer"]["devices"] = DEVICES

    # Remove stale dataset path so vak prep regenerates it
    train_section = config["vak"]["train"]
    if "dataset" in train_section and "path" in train_section["dataset"]:
        del train_section["dataset"]["path"]

    with open(TRAIN_TOML, "w", encoding="utf-8") as f:
        tomlkit.dump(config, f)

    print(f"  ✓ config_train.toml updated")
    print(f"    data_dir   = {data_dir}")
    print(f"    output_dir = {PREP_TRAIN_DIR}")


def update_predict_toml(data_dir: str, output_dir: str):
    """Update config_predict.toml with new data_dir and reset dataset path."""
    with open(PREDICT_TOML, "r", encoding="utf-8") as f:
        config = tomlkit.load(f)

    config["vak"]["prep"]["data_dir"]   = data_dir
    config["vak"]["prep"]["output_dir"] = output_dir
    config["vak"]["train"]["trainer"]["accelerator"] = ACCELERATOR
    config["vak"]["train"]["trainer"]["devices"] = DEVICES

    # Remove stale dataset path so vak prep regenerates it
    predict_section = config["vak"]["predict"]
    if "dataset" in predict_section and "path" in predict_section["dataset"]:
        del predict_section["dataset"]["path"]

    with open(PREDICT_TOML, "w", encoding="utf-8") as f:
        tomlkit.dump(config, f)

    print(f"  ✓ config_predict.toml updated")
    print(f"    data_dir   = {data_dir}")
    print(f"    output_dir = {output_dir}")


# ── vak prep runner ───────────────────────────────────────────────────────────

def run_vak_prep(toml_path: str):
    print(f"\n  Running: vak prep {Path(toml_path).name}")
    subprocess.run(
        [VAK_PYTHON, "-m", "vak", "prep", toml_path],
        check=True,
    )
    print(f"  ✓ vak prep completed")


# ── Main pipeline ─────────────────────────────────────────────────────────────

def prepare_training(audio_dir: str, annot_dir: str):
    """
    Split all wav files in audio_dir with matching annotations in annot_dir,
    then run vak prep on the combined output directory.
    """
    audio_dir = Path(audio_dir)
    annot_dir = Path(annot_dir)

    output_dir = Path(SEGMENT_ROOT) / "train_data"
    if output_dir.exists():
        print(f"  Clearing existing segment dir: {output_dir}")
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True)

    wav_files = sorted(audio_dir.glob("*.wav"))
    if not wav_files:
        raise FileNotFoundError(f"No .wav files found in {audio_dir}")

    print(f"\nFound {len(wav_files)} audio file(s) in {audio_dir}")

    for wav in wav_files:
        annot = find_annotation(wav.stem, annot_dir)
        if annot is None:
            print(f"  ⚠ No annotation found for {wav.name}, skipping")
            continue
        print(f"\n  Processing: {wav.name}  ←→  {annot.name}")
        split_audio_and_annotations(
            audio_path=str(wav),
            output_dir=str(output_dir),
            annot_path=str(annot),
        )

    print(f"\n[Config] Updating config_train.toml...")
    update_train_toml(data_dir=str(output_dir))

    print(f"\n[vak prep] Preparing training dataset...")
    run_vak_prep(TRAIN_TOML)


def prepare_test_or_predict(audio_dir: str, annot_dir: str | None, mode: str):
    """
    Split all wav files (each into its own subfolder), then run vak prep
    per file (predict mode) or on the combined folder (test mode).
    """
    audio_dir = Path(audio_dir)
    annot_dir = Path(annot_dir) if annot_dir else None

    prep_output = PREP_TEST_DIR if mode == "test" else PREP_PREDICT_DIR

    wav_files = sorted(audio_dir.glob("*.wav"))
    if not wav_files:
        raise FileNotFoundError(f"No .wav files found in {audio_dir}")

    print(f"\nFound {len(wav_files)} audio file(s) in {audio_dir}")

    for wav in wav_files:
        recorder_name = wav.stem
        seg_out = Path(SEGMENT_ROOT) / f"{mode}_data" / recorder_name

        if seg_out.exists():
            print(f"\n  Clearing existing segment dir: {seg_out}")
            shutil.rmtree(seg_out)
        seg_out.mkdir(parents=True)

        # Find annotation if test mode
        annot = None
        if mode == "test" and annot_dir:
            annot = find_annotation(recorder_name, annot_dir)
            if annot is None:
                print(f"  ⚠ No annotation found for {wav.name} (test mode), skipping annotations")
            else:
                print(f"\n  Processing: {wav.name}  ←→  {annot.name}")
        else:
            print(f"\n  Processing: {wav.name}  (no annotation needed)")

        split_audio_and_annotations(
            audio_path=str(wav),
            output_dir=str(seg_out),
            annot_path=str(annot) if annot else None,
        )

        # Update config and run vak prep for each recorder separately
        print(f"\n  [Config] Updating config_predict.toml for {recorder_name}...")
        update_predict_toml(
            data_dir=str(seg_out),
            output_dir=prep_output,
        )

        print(f"\n  [vak prep] Preparing {mode} dataset for {recorder_name}...")
        run_vak_prep(PREDICT_TOML)


# ── CLI ───────────────────────────────────────────────────────────────────────

def main():
    # Default audio/annot dirs come from config.py; can still be overridden on CLI
    _AUDIO_DEFAULTS = {
        "train":   RAW_AUDIO_TRAIN,
        "test":    RAW_AUDIO_TEST,
        "predict": RAW_AUDIO_PREDICT,
    }
    _ANNOT_DEFAULTS = {
        "train": RAW_ANNOT_TRAIN,
        "test":  RAW_ANNOT_TEST,
    }

    parser = argparse.ArgumentParser(
        description="Batch data preparation for petrel detection project. "
                    "Paths default to values in config.py."
    )
    parser.add_argument(
        "--mode",
        choices=["train", "test", "predict"],
        required=True,
        help="Data type: train / test / predict",
    )
    parser.add_argument(
        "--audio_dir",
        default=None,
        help="Override audio directory from config.py",
    )
    parser.add_argument(
        "--annot_dir",
        default=None,
        help="Override annotation directory from config.py",
    )

    args = parser.parse_args()

    # Resolve paths: CLI arg takes priority over config.py default
    audio_dir = args.audio_dir or _AUDIO_DEFAULTS[args.mode]
    annot_dir = args.annot_dir or _ANNOT_DEFAULTS.get(args.mode)

    if args.mode == "train" and annot_dir is None:
        parser.error(
            "--annot_dir is required for train mode (or set RAW_ANNOT_TRAIN in config.py)"
        )

    print(f"\n{'=' * 60}")
    print(f"Mode        : {args.mode.upper()}")
    print(f"Audio dir   : {audio_dir}")
    print(f"Annot dir   : {annot_dir or '(not required)'}")
    print(f"{'=' * 60}")

    if args.mode == "train":
        prepare_training(audio_dir=audio_dir, annot_dir=annot_dir)
    else:
        prepare_test_or_predict(audio_dir=audio_dir, annot_dir=annot_dir, mode=args.mode)

    print(f"\n✅ All done — {args.mode.upper()} data preparation complete.")


if __name__ == "__main__":
    main()